cisco_app/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('router/', include('router.urls')),
    path('api/', include('myapi.urls')),
    path('api-token-auth/', views.obtain_auth_token),
]

myapi/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('router/', views.RouterView.as_view()),
    path('router/<int:pk>', views.RouterView.as_view()),
    path('router/<str:ip>', views.RouterView.as_view()),
]

router/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('show',views.show),
    path('add',views.add),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
]

myapi/models.py
from django.db import models

# Create your models here.

router/models.py
from django.db import models

class RouterDetails(models.Model):  
    sapid = models.CharField(max_length=18,blank=False,null=False)  
    loopback = models.CharField(max_length=15,blank=False,null=False)  
    hostname = models.CharField(max_length=15,blank=False,null=False)
    mac_address = models.CharField(max_length=17,blank=False,null=False)
    status = models.BooleanField(default=True,blank=False,null=False)  
    class Meta:  
        db_table = "router_details"
        unique_together = ['loopback','hostname'] 

router/forms.py
from django import forms  
from .models import RouterDetails

class RouterForm(forms.ModelForm):  
    class Meta:  
        model = RouterDetails 
        fields = "__all__" 

myapi/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from router.models import RouterDetails
from .seriealizers import RouterSerializer
from rest_framework import status

class RouterView(APIView):
    permission_classes = (IsAuthenticated,)

    def get_object(self, pk):
        try:
            return RouterDetails.objects.get(pk=pk,status=1)
        except RouterDetails.DoesNotExist:
            return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self,request,pk=None):
        if pk != None:
            router = self.get_object(pk=pk)
            result = RouterSerializer(router)
        else:
            router = RouterDetails.objects.all().filter(status=1)
            result = RouterSerializer(router,many=True)       
        return Response(data=result.data,status=status.HTTP_200_OK)

    def post(self,request):
        serializer = RouterSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(data=serializer.data,status=status.HTTP_201_CREATED)
        return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def put(self,request,pk=None,ip=None):
        router = []
        if pk != None:
            router = self.get_object(pk=pk)
        elif ip != None:
            router = RouterDetails.objects.filter(status=1,loopback__exact=ip)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        serializer = RouterSerializer(router,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self,request,pk):
        router = RouterDetails.objects.filter(pk=pk)
        router.update(status=0)
        return Response(status=status.HTTP_204_NO_CONTENT)

router/views.py
from django.shortcuts import render, redirect  
from .forms import RouterForm  
from .models import RouterDetails
from django.db.models import Q
from django.template.loader import render_to_string
from django.http import JsonResponse

# Create your views here.  
def add(request):  
    if request.method == "POST":  
        form = RouterForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('show')  
            except:  
                pass  
    else:  
        form = RouterForm()  
    return render(request,'index.html',{'form':form})  
def show(request):
    ctx = {}
    param = request.GET.get('q')
    if param:
        routerDetails = RouterDetails.objects.filter(Q(status=1),Q(hostname__icontains=param) | Q(sapid__icontains = param) | Q(loopback__icontains = param) | Q(mac_address__icontains = param))
    else:
        routerDetails = RouterDetails.objects.all().filter(status=1)

    if request.is_ajax():
        html = render_to_string(
            template_name="records.html", 
            context={"routerDetails": routerDetails}
        )
        data_dict = {"html_from_view": html}
        return JsonResponse(data=data_dict, safe=False)
        
    ctx = {'routerDetails':routerDetails}
    return render(request,"show.html", context=ctx)  
def edit(request, id):  
    routerDetails = RouterDetails.objects.get(id=id)  
    return render(request,'edit.html', {'routerDetails':routerDetails})  
def update(request, id):  
    routerDetails = RouterDetails.objects.get(id=id)  
    form = RouterForm(request.POST, instance = routerDetails)  
    if form.is_valid():  
        form.save()  
        return redirect("/router/show")  
    return render(request, 'edit.html', {'routerDetails': routerDetails})  
def destroy(request, id):  
    routerDetails = RouterDetails.objects.filter(id=id)  
    routerDetails.update(status=0)  
    return redirect("/router/show")

router/templates/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Router Records</title>  
     {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>  
<body>
{% block content %}
{% endblock %}

{% block footer %}
  <script type="text/javascript" src="{% static 'javascript/main.js' %}"></script>
{% endblock %} 
</body>
</html>

router/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/router/update/{{routerDetails.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">SAP Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="sapid" id="id_sapid" required maxlength="18" value="{{ routerDetails.sapid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Hostname:</label>  
    <div class="col-sm-4">  
        <input type="text" name="hostname" id="id_hostname" required maxlength="14" value="{{ routerDetails.hostname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Loopback:</label>  
    <div class="col-sm-4">  
        <input type="text" name="loopback" id="id_loopback" required maxlength="15" value="{{ routerDetails.loopback }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mac Address:</label>  
    <div class="col-sm-4">  
        <input type="text" name="mac_address" id="id_mac_address" required maxlength="17" value="{{ routerDetails.mac_address }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>

router/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="add">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">SAP Id:</label>  
    <div class="col-sm-4">  
      {{ form.sapid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Hostname:</label>  
    <div class="col-sm-4">  
      {{ form.hostname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Loopback:</label>  
    <div class="col-sm-4">  
      {{ form.loopback }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">MAC Address:</label>  
    <div class="col-sm-4">  
      {{ form.mac_address }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

router/templates/records.html
{% for router in routerDetails %}  
    <tr>  
        <td>{{ router.sapid }}</td>  
        <td>{{ router.hostname }}</td>  
        <td>{{ router.loopback }}</td>  
        <td>{{ router.mac_address }}</td>  
        <td>  
            <a href="edit/{{ router.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="delete/{{ router.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}

router/templates/show.html
{% extends 'base.html' %}

{% block content %}
    <input type="text" name="search" id="id_search"/>
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>SAP ID</th>  
        <th>Hostname</th>  
        <th>Loopback</th>  
        <th>MAC Address</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
        {% include 'records.html' %}
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="add" class="btn btn-primary">Add New Record</a></center>  
{% endblock %}